INSERT INTO player (firstname, lastname, birth_date, position, nationality, retired) VALUES
                                                                                         ('Cristiano', 'Ronaldo',      '1985-02-05', 'Attaquant', 'Portugal',      false),
                                                                                         ('Thierry',   'Henry',        '1977-08-17', 'Attaquant', 'France',        true),
                                                                                         ('Zlatan',    'Ibrahimovic',  '1981-10-03', 'Attaquant', 'Suede',         true),
                                                                                         ('Didier',    'Drogba',       '1978-03-11', 'Attaquant', 'Cote d Ivoire', true),
                                                                                         ('Andrea',    'Pirlo',        '1979-05-19', 'Milieu',    'Italie',        true),
                                                                                         ('Luka',      'Modric',       '1985-09-09', 'Milieu',    'Croatie',       false),
                                                                                         ('NGolo',    'Kante',        '1991-03-29', 'Milieu',    'France',        false),
                                                                                         ('Iker',      'Casillas',     '1981-05-20', 'Gardien',   'Espagne',       true);

INSERT INTO club (name, country, league, created_in) VALUES
                                                        ('AS Cannes',           'France',           'National 2',       1902),
                                                        ('Girondins de Bordeaux',  'France',           'Ligue 2',          1881),
                                                        ('AS Monaco',           'France',           'Ligue 1',          1924),
                                                        ('Paris Saint-Germain', 'France',           'Ligue 1',          1970),
                                                        ('Olympique de Marseille', 'France',           'Ligue 1',          1899),
                                                        ('Le Mans FC',          'France',           'National',         1985),
                                                        ('EA Guingamp',         'France',           'Ligue 2',          1912),
                                                        ('SM Caen',             'France',           'Ligue 2',          1913),
                                                        ('US Boulogne',         'France',           'National',         1898),
                                                        ('Juventus',            'Italie',           'Serie A',          1897),
                                                        ('AC Milan',            'Italie',           'Serie A',          1899),
                                                        ('Inter Milan',         'Italie',           'Serie A',          1908),
                                                        ('Brescia',             'Italie',           'Serie B',          1911),
                                                        ('Real Madrid',         'Espagne',          'La Liga',          1902),
                                                        ('FC Barcelone',        'Espagne',          'La Liga',          1899),
                                                        ('Manchester United',   'Angleterre',       'Premier League',   1878),
                                                        ('Arsenal',             'Angleterre',       'Premier League',   1886),
                                                        ('Chelsea',             'Angleterre',       'Premier League',   1905),
                                                        ('Tottenham',           'Angleterre',       'Premier League',   1882),
                                                        ('Leicester City',      'Angleterre',       'Premier League',   1884),
                                                        ('Ajax Amsterdam',      'Pays-Bas',         'Eredivisie',       1900),
                                                        ('Sporting CP',         'Portugal',         'Primeira Liga',    1906),
                                                        ('FC Porto',            'Portugal',         'Primeira Liga',    1893),
                                                        ('Malmo FF',            'Suede',            'Allsvenskan',      1910),
                                                        ('Dinamo Zagreb',       'Croatie',          'HNL',              1911),
                                                        ('Galatasaray',         'Turquie',          'Super Lig',        1905),
                                                        ('Al-Nassr',            'Arabie Saoudite',  'Saudi Pro League', 1955),
                                                        ('Al-Ittihad',          'Arabie Saoudite',  'Saudi Pro League', 1927),
                                                        ('Shanghai Shenhua',    'Chine',            'Super League',     1993),
                                                        ('Inter Miami',         'Etats-Unis',       'MLS',              2018),
                                                        ('New York Red Bulls',  'Etats-Unis',       'MLS',              1994),
                                                        ('New York City FC',    'Etats-Unis',       'MLS',              2013);

INSERT INTO contract (player_id, club, start_year, end_year) VALUES
                                                              -- Zidane
                                                              ((SELECT player_id FROM player WHERE lastname='Zidane'),      (SELECT club_id FROM club WHERE name='AS Cannes'),           1988, 1992),
                                                              ((SELECT player_id FROM player WHERE lastname='Zidane'),      (SELECT club_id FROM club WHERE name='Girondins de Bordeaux'),  1992, 1996),
                                                              ((SELECT player_id FROM player WHERE lastname='Zidane'),      (SELECT club_id FROM club WHERE name='Juventus'),            1996, 2001),
                                                              ((SELECT player_id FROM player WHERE lastname='Zidane'),      (SELECT club_id FROM club WHERE name='Real Madrid'),         2001, 2006),
                                                              -- Mbappe
                                                              ((SELECT player_id FROM player WHERE lastname='Mbappe'),      (SELECT club_id FROM club WHERE name='AS Monaco'),           2015, 2017),
                                                              ((SELECT player_id FROM player WHERE lastname='Mbappe'),      (SELECT club_id FROM club WHERE name='Paris Saint-Germain'), 2017, 2024),
                                                              ((SELECT player_id FROM player WHERE lastname='Mbappe'),      (SELECT club_id FROM club WHERE name='Real Madrid'),         2024, NULL),
                                                              -- Messi
                                                              ((SELECT player_id FROM player WHERE lastname='Messi'),       (SELECT club_id FROM club WHERE name='FC Barcelone'),        2004, 2021),
                                                              ((SELECT player_id FROM player WHERE lastname='Messi'),       (SELECT club_id FROM club WHERE name='Paris Saint-Germain'), 2021, 2023),
                                                              ((SELECT player_id FROM player WHERE lastname='Messi'),       (SELECT club_id FROM club WHERE name='Inter Miami'),         2023, NULL),
                                                              -- Cristiano Ronaldo
                                                              ((SELECT player_id FROM player WHERE lastname='Ronaldo'),     (SELECT club_id FROM club WHERE name='Sporting CP'),         2002, 2003),
                                                              ((SELECT player_id FROM player WHERE lastname='Ronaldo'),     (SELECT club_id FROM club WHERE name='Manchester United'),   2003, 2009),
                                                              ((SELECT player_id FROM player WHERE lastname='Ronaldo'),     (SELECT club_id FROM club WHERE name='Real Madrid'),         2009, 2018),
                                                              ((SELECT player_id FROM player WHERE lastname='Ronaldo'),     (SELECT club_id FROM club WHERE name='Juventus'),            2018, 2021),
                                                              ((SELECT player_id FROM player WHERE lastname='Ronaldo'),     (SELECT club_id FROM club WHERE name='Manchester United'),   2021, 2022),
                                                              ((SELECT player_id FROM player WHERE lastname='Ronaldo'),     (SELECT club_id FROM club WHERE name='Al-Nassr'),            2023, NULL),
                                                              -- Henry
                                                              ((SELECT player_id FROM player WHERE lastname='Henry'),       (SELECT club_id FROM club WHERE name='AS Monaco'),           1994, 1999),
                                                              ((SELECT player_id FROM player WHERE lastname='Henry'),       (SELECT club_id FROM club WHERE name='Juventus'),            1999, 1999),
                                                              ((SELECT player_id FROM player WHERE lastname='Henry'),       (SELECT club_id FROM club WHERE name='Arsenal'),             1999, 2007),
                                                              ((SELECT player_id FROM player WHERE lastname='Henry'),       (SELECT club_id FROM club WHERE name='FC Barcelone'),        2007, 2010),
                                                              ((SELECT player_id FROM player WHERE lastname='Henry'),       (SELECT club_id FROM club WHERE name='New York Red Bulls'),  2010, 2014),
                                                              -- Ibrahimovic
                                                              ((SELECT player_id FROM player WHERE lastname='Ibrahimovic'), (SELECT club_id FROM club WHERE name='Malmo FF'),            1999, 2001),
                                                              ((SELECT player_id FROM player WHERE lastname='Ibrahimovic'), (SELECT club_id FROM club WHERE name='Ajax Amsterdam'),      2001, 2004),
                                                              ((SELECT player_id FROM player WHERE lastname='Ibrahimovic'), (SELECT club_id FROM club WHERE name='Juventus'),            2004, 2006),
                                                              ((SELECT player_id FROM player WHERE lastname='Ibrahimovic'), (SELECT club_id FROM club WHERE name='Inter Milan'),         2006, 2009),
                                                              ((SELECT player_id FROM player WHERE lastname='Ibrahimovic'), (SELECT club_id FROM club WHERE name='FC Barcelone'),        2009, 2010),
                                                              ((SELECT player_id FROM player WHERE lastname='Ibrahimovic'), (SELECT club_id FROM club WHERE name='AC Milan'),            2010, 2012),
                                                              ((SELECT player_id FROM player WHERE lastname='Ibrahimovic'), (SELECT club_id FROM club WHERE name='Paris Saint-Germain'), 2012, 2016),
                                                              ((SELECT player_id FROM player WHERE lastname='Ibrahimovic'), (SELECT club_id FROM club WHERE name='Manchester United'),   2016, 2018),
                                                              ((SELECT player_id FROM player WHERE lastname='Ibrahimovic'), (SELECT club_id FROM club WHERE name='AC Milan'),            2020, 2023),
                                                              -- Drogba
                                                              ((SELECT player_id FROM player WHERE lastname='Drogba'),      (SELECT club_id FROM club WHERE name='Le Mans FC'),          1998, 2002),
                                                              ((SELECT player_id FROM player WHERE lastname='Drogba'),      (SELECT club_id FROM club WHERE name='EA Guingamp'),         2002, 2003),
                                                              ((SELECT player_id FROM player WHERE lastname='Drogba'),      (SELECT club_id FROM club WHERE name='Olympique de Marseille'), 2003, 2004),
                                                              ((SELECT player_id FROM player WHERE lastname='Drogba'),      (SELECT club_id FROM club WHERE name='Chelsea'),             2004, 2012),
                                                              ((SELECT player_id FROM player WHERE lastname='Drogba'),      (SELECT club_id FROM club WHERE name='Shanghai Shenhua'),    2012, 2013),
                                                              ((SELECT player_id FROM player WHERE lastname='Drogba'),      (SELECT club_id FROM club WHERE name='Galatasaray'),         2013, 2014),
                                                              ((SELECT player_id FROM player WHERE lastname='Drogba'),      (SELECT club_id FROM club WHERE name='Chelsea'),             2014, 2015),
                                                              -- Pirlo
                                                              ((SELECT player_id FROM player WHERE lastname='Pirlo'),       (SELECT club_id FROM club WHERE name='Brescia'),             1995, 1998),
                                                              ((SELECT player_id FROM player WHERE lastname='Pirlo'),       (SELECT club_id FROM club WHERE name='Inter Milan'),         1998, 2001),
                                                              ((SELECT player_id FROM player WHERE lastname='Pirlo'),       (SELECT club_id FROM club WHERE name='AC Milan'),            2001, 2011),
                                                              ((SELECT player_id FROM player WHERE lastname='Pirlo'),       (SELECT club_id FROM club WHERE name='Juventus'),            2011, 2015),
                                                              ((SELECT player_id FROM player WHERE lastname='Pirlo'),       (SELECT club_id FROM club WHERE name='New York City FC'),    2015, 2017),
                                                              -- Modric
                                                              ((SELECT player_id FROM player WHERE lastname='Modric'),      (SELECT club_id FROM club WHERE name='Dinamo Zagreb'),       2003, 2008),
                                                              ((SELECT player_id FROM player WHERE lastname='Modric'),      (SELECT club_id FROM club WHERE name='Tottenham'),           2008, 2012),
                                                              ((SELECT player_id FROM player WHERE lastname='Modric'),      (SELECT club_id FROM club WHERE name='Real Madrid'),         2012, NULL),
                                                              -- Kante
                                                              ((SELECT player_id FROM player WHERE lastname='Kante'),       (SELECT club_id FROM club WHERE name='US Boulogne'),         2012, 2013),
                                                              ((SELECT player_id FROM player WHERE lastname='Kante'),       (SELECT club_id FROM club WHERE name='SM Caen'),             2013, 2015),
                                                              ((SELECT player_id FROM player WHERE lastname='Kante'),       (SELECT club_id FROM club WHERE name='Leicester City'),      2015, 2016),
                                                              ((SELECT player_id FROM player WHERE lastname='Kante'),       (SELECT club_id FROM club WHERE name='Chelsea'),             2016, 2023),
                                                              ((SELECT player_id FROM player WHERE lastname='Kante'),       (SELECT club_id FROM club WHERE name='Al-Ittihad'),          2023, NULL),
                                                              -- Casillas
                                                              ((SELECT player_id FROM player WHERE lastname='Casillas'),    (SELECT club_id FROM club WHERE name='Real Madrid'),         1999, 2015),
                                                              ((SELECT player_id FROM player WHERE lastname='Casillas'),    (SELECT club_id FROM club WHERE name='FC Porto'),            2015, 2020);